language: ruby
rvm:
- 2.5.1
install:
- bundle install
- nvm install node
- node -v
- npm i -g yarn
- yarn
script:
- bundle exec rails webpacker:compile
- bundle exec rake
cache:
  bundler: true
  directories:
  - node_modules
  yarn: true
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_ID
  secret_access_key: $SECRET_KEY
  region: us-east-1
  app: unfuckyourfinances
  env: unfuckyourfinances-env
  bucket_name: elasticbeanstalk-us-east-1-381263952706
  on:
    repo: GabrielGLevine/unfuckyourfinances
