language: ruby
rvm:
- 2.5.1
install:
- bundle install
cache: bundler
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_ID
  secret_access_key: $SECRET_KEY
  region: us-east-1
  app: packthehouse
  env: packthehouse-env
  bucket_name: elasticbeanstalk-us-east-1-381263952706
  on:
    repo: GabrielGLevine/packthehouse
