language: ruby
rvm:
- 2.5.1
install:
- bundle install
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
before_install:
- sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
- sudo service postgresql restart
- sleep 1
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
cache: bundler
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_ID
  secret_access_key: $SECRET_KEY
  region: us-east-1
  app: packthehouse
  env: packthehouse-env
  bucket_name: elasticbeanstalk-us-east-1-381263952706
  on:
    repo: GabrielGLevine/packthehouse
